---
title: BI Developer | Data Engineer | Machine Learning Engineer | Cloud Data Architect
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://junlulocky.com
baseurl: "/PanelCV"
yourname: Allan Situma
location: San Francisco , CA
linkedin: http://www.linkedin.com
